### ISSUE TITLE
support synchronous `gpt_json.run` etc

### ISSUE THREAD

**Issue by craterink** [piercefreeman/gpt-json#14]
Some program execution environments aren't very supportive of asyncio, e.g. when running flask_socketio:
https://stackoverflow.com/questions/64972142/running-asyncio-and-socketio-at-the-same-time-in-python

**Comment by piercefreeman** [comment]
I'm not 100% convinced that a synchronous implementation is a good idea here. Since the response times with OpenAI - even in the streaming case - are pretty lengthy, a synchronous wrapper would fully block server responses for whatever duration the API is taking to respond. And that could be as high as a couple of minutes.

Granted users could scale this up with multithreading/multiprocessing to still accept requests while the sync requests are pending. But given the almost guaranteed network latencies here, I'm almost of the mind that you should switch to an async runloop (like with fastapi, starlette, or others) instead of us trying to support the synchronous use-case.

What do you think @craterink?

**Comment by craterink** [comment]
yepp, maybe my setup is odd, I'll try switching to fastapi a bit later and see if that resolves the issue

**Comment by craterink** [comment]
Closing for now, will re-open if it's quite difficult to port to a supportive environment
