### ISSUE TITLE
Configure number of retries

### ISSUE THREAD

**Issue by andrscyv** [piercefreeman/gpt-json#30]
Hi!

Your package is very useful !!

I've noticed a message being logged about the library retrying the api call to openai

How many retries will the library do ? Is there a way to control the max amount of retries ? 

I just want to make sure I dont spend more than certain limit

**Comment by piercefreeman** [comment]
Hi @andrscyv, the default count of retries is 3 (which I empirically found to be the right number given API failures). You can control this via the `openai_max_retries` [keyword](https://github.com/piercefreeman/gpt-json/blob/main/gpt_json/gpt.py#L73) argument when you initialize GPTJSON.

```python
GPTJSON(openai_max_retries=1)
```

I'll also note that this retry only is attempted if there are system [connection](https://github.com/piercefreeman/gpt-json/blob/main/gpt_json/gpt.py#L151) issues - specifically RateLimitError, OpenAITimeout, and APIConnectionError. While I can't guarantee behavior in all cases, you really shouldn't be getting billed for these since no value is actually coming down to the client.

**Comment by andrscyv** [comment]
Thanks for the clarification!

So its the openai library that does the retries right ? not gptjson

**Comment by piercefreeman** [comment]
The other way; GPTJSON has its own retry logic but that wraps openai provided exceptions. So only when those common exceptions are raised will we retry the query.
