### ISSUE TITLE
Why async?

### ISSUE THREAD

**Issue by ptyshcop** [piercefreeman/gpt-json#36]
Hi there, any particular reason why `GPTJSON.run()` is async?

Glancing through the code, I can't notice anything specific that requires async or makes library users life easier.

**Comment by piercefreeman** [comment]
Yes, three main reasons that are motivated from where users would call this library.

1. It's trivial to wrap async calls in sync code with asyncio.run, but harder to make synchronous code async if you have a deployment where async behavior is desired
2. Most web frameworks are adopting async as a supported or even preferred handler convention (see FastAPI and Temporalio)
3. The bulk of the time with LLMs is spent waiting for network responses where the CPU is otherwise idle, so it makes sense to yield event loop execution over to other tasks explicitly
